apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: url-shortener
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
images:
  - name: urlshortenerpf9nt4acr.azurecr.io/url-shortener
    newTag: 445686d4ae4816596a3f4889dbb5775d8a09cba0
