apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: url-shortener
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
images:
  - name: urlshortenerpf9nt4acr.azurecr.io/url-shortener
    newTag: 6c0476092ac8ea81f4fb7e80139af859de25cb36
