apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: url-shortener
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
images:
  - name: urlshortenerpf9nt4acr.azurecr.io/url-shortener
    newTag: 0b73bb7059c084d127b3630c5dd33044270aebff
