apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - secret-provider-class.yaml
  - deployment.yaml
  - service.yaml
  - migration-job.yaml
  - smoke-test-job.yaml
