apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: url-shortener-key-vault
  namespace: url-shortener
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider: azure
  secretObjects:
    - secretName: url-shortener-config
      type: Opaque
      data:
        - objectName: database-url
          key: DATABASE_URL
  parameters:
    usePodIdentity: "false"
    clientID: "a4d29c94-71d0-4e3d-b010-2b3a1d99f3ca"
    keyvaultName: "urlshortener-pf9nt4-kv"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
          objectVersion: ""
    tenantId: "3db27ecc-1791-4dda-9b51-798adfa4a3ca"
