apiVersion: v1
kind: ServiceAccount
metadata:
  name: url-shortener
  namespace: url-shortener
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
    azure.workload.identity/client-id: "a4d29c94-71d0-4e3d-b010-2b3a1d99f3ca"
